export const labels = {
  title: 'Kura',
  overview: 'Übersicht',
  subscriptions: 'Abonnements',
  history: 'Verlauf',
  immich: 'Immich',
  limits: 'Limits',
  skipToContent: 'Zum Inhalt springen',
  menu: 'Menü',
  mainNavigation: 'Hauptnavigation',
  systemStatus: 'Systemstatus',
  quickLinks: 'Schnellzugriff',
  quickSubscriptions: 'Ziele beobachten und Zeitpläne festlegen',
  quickHistory: 'Gespeicherte Beiträge und Dateien ansehen',
  quickImmich: 'Verbindung einrichten und testen',
  unknown: 'unbekannt',
  yes: 'Ja',
  no: 'Nein',
  statusErrorAction: 'Prüfen Sie, ob der Dienst läuft, und laden Sie die Seite neu.',
  version: 'Version',
  testSurface: 'Testoberfläche',
  insecureConnection: 'Verbindung unverschlüsselt (HTTP), nur Testbetrieb',
  service: 'Dienst',
  database: 'Datenbank',
  available: 'Erreichbar',
  unavailable: 'Fehler',
  databaseAvailable: 'Datenbank erreichbar',
  lastUpdated: 'Letzter Abruf',
  migrations: 'Angewendete Migrationen',
  latestMigration: 'Letzte Version',
  loading: 'Wird abgerufen …',
  loadingPage: 'Anmeldung wird geprüft …',
  setupTitle: 'Kura einrichten',
  setupIntro: 'Legen Sie das erste Administratorkonto an.',
  displayName: 'Anzeigename',
  username: 'Benutzername',
  password: 'Passwort',
  passwordRepeat: 'Passwort wiederholen',
  setupToken: 'Einrichtungs-Token',
  setupTokenHint: 'Nur erforderlich, wenn der Dienst einen Token verlangt.',
  passwordHint: 'Mindestens 12 Zeichen; häufige Passwörter sind nicht erlaubt.',
  setupSubmit: 'Einrichtung abschließen',
  loginTitle: 'Anmelden',
  loginSubmit: 'Anmelden',
  loginFailed: 'Anmeldung fehlgeschlagen. Prüfen Sie Benutzername und Passwort.',
  ssoLogin: 'Mit SSO anmelden',
  ssoLoginFailed: 'Die SSO-Anmeldung ist fehlgeschlagen. Bitte versuchen Sie es erneut oder verwenden Sie die lokale Anmeldung.',
  logout: 'Abmelden',
  account: 'Konto',
  users: 'Benutzerverwaltung',
  changePasswordTitle: 'Passwort ändern',
  changePasswordRequired: 'Passwortänderung erforderlich',
  changePasswordRequiredHint: 'Ändern Sie Ihr Anfangspasswort, bevor Sie fortfahren.',
  currentPassword: 'Aktuelles Passwort',
  newPassword: 'Neues Passwort',
  changePasswordSubmit: 'Passwort ändern',
  passwordMismatch: 'Die Passwortwiederholung stimmt nicht überein.',
  save: 'Speichern',
  userNameColumn: 'Name',
  userUsernameColumn: 'Benutzername',
  userRoleColumn: 'Rolle',
  userStatusColumn: 'Status',
  userCreatedColumn: 'Angelegt am',
  userActionsColumn: 'Aktionen',
  adminRole: 'Administrator',
  userRole: 'Benutzer',
  active: 'Aktiv',
  blocked: 'Gesperrt',
  createUser: 'Benutzer anlegen',
  createUserTitle: 'Neuen Benutzer anlegen',
  initialPassword: 'Anfangspasswort',
  role: 'Rolle',
  cancel: 'Abbrechen',
  lock: 'Sperren',
  unlock: 'Entsperren',
  lockConfirm: 'Benutzer wirklich sperren?',
  unlockConfirm: 'Benutzer wirklich entsperren?',
  close: 'Schließen',
  requestError: 'Die Anfrage konnte nicht verarbeitet werden.',
  noUsers: 'Keine Benutzer vorhanden.',
  statusError: 'Der Dienststatus konnte nicht abgerufen werden.'
} as const;
