export const labels = {
  title: 'Kura',
  overview: 'Übersicht',
  overviewLoadFailed: 'Die Übersicht konnte nicht geladen werden.',
  overviewLoadFailedAction: 'Prüfe, ob der Dienst läuft, und lade die Seite neu.',
  reload: 'Erneut laden',
  emptyArchive: 'Noch nichts im Archiv.',
  emptyArchiveHint: 'Lege dein erstes Abonnement an. Kura holt neue Beiträge dann automatisch.',
  createSubscription: 'Abonnement anlegen',
  recentlyLoaded: 'Zuletzt geladen',
  allMedia: 'Alle Medien',
  runningNow: 'Läuft gerade',
  nextUp: 'Als Nächstes',
  lastRan: 'Zuletzt gelaufen',
  openHistory: 'Verlauf öffnen',
  technical: 'Technik',
  needsYou: 'Braucht dich',
  renewAccess: 'Zugang erneuern',
  nothingRunning: 'Gerade lädt nichts.',
  media: 'Medien',
  mediaEmpty: 'Noch keine Medien.',
  mediaEmptyHint: 'Sobald Kura etwas lädt, erscheint es hier.',
  allSubscriptions: 'Alle Abonnements',
  loadMore: 'Weitere 40 laden',
  mediaShort: 'Medien',
  subscriptionsShort: 'Abos',
  administration: 'Verwaltung',
  more: 'Mehr',
  subscriptions: 'Abonnements',
  history: 'Verlauf',
  immich: 'Immich',
  limits: 'Limits',
  skipToContent: 'Zum Inhalt springen',
  menu: 'Menü',
  mainNavigation: 'Hauptnavigation',
  systemStatus: 'Systemstatus',
  quickLinks: 'Schnellzugriff',
  quickSubscriptions: 'Ziele beobachten und Zeitpläne festlegen',
  quickHistory: 'Gespeicherte Beiträge und Dateien ansehen',
  quickImmich: 'Verbindung einrichten und testen',
  unknown: 'unbekannt',
  yes: 'Ja',
  no: 'Nein',
  statusErrorAction: 'Prüfe, ob der Dienst läuft, und lade die Seite neu.',
  version: 'Version',
  testSurface: 'Testbetrieb',
  insecureConnection: 'Die Verbindung ist unverschlüsselt (HTTP).',
  /** The same warning for a narrow strip, where the long text would be cut off and lose "HTTP". */
  insecureShort: 'unverschlüsselt (HTTP)',
  service: 'Dienst',
  database: 'Datenbank',
  available: 'Erreichbar',
  unavailable: 'Fehler',
  databaseAvailable: 'Datenbank erreichbar',
  lastUpdated: 'Letzter Abruf',
  migrations: 'Angewendete Migrationen',
  latestMigration: 'Letzte Version',
  loading: 'Wird abgerufen …',
  loadingPage: 'Anmeldung wird geprüft …',
  setupTitle: 'Willkommen bei Kura',
  setupIntro: 'Ein Konto für dich als Administrator, dann kann es losgehen.',
  loginTitle: 'Anmelden',
  loginLede: 'Dein Archiv für Bilder und Videos.',
  displayName: 'Anzeigename',
  username: 'Benutzername',
  password: 'Passwort',
  passwordRepeat: 'Passwort wiederholen',
  setupToken: 'Einrichtungs-Token',
  setupTokenHint: 'Nur erforderlich, wenn der Dienst einen Token verlangt.',
  passwordHint: 'Mindestens 12 Zeichen; häufige Passwörter sind nicht erlaubt.',
  setupSubmit: 'Einrichtung abschließen',
  loginSubmit: 'Anmelden',
  loginFailed: 'Das hat nicht geklappt. Prüfe Benutzername und Passwort und versuche es noch einmal.',
  ssoLogin: 'Mit SSO anmelden',
  ssoLoginFailed: 'Die Anmeldung über SSO ist fehlgeschlagen. Versuche es noch einmal oder melde dich mit Benutzername und Passwort an.',
  logout: 'Abmelden',
  account: 'Konto',
  users: 'Benutzerverwaltung',
  changePasswordTitle: 'Passwort ändern',
  changePasswordRequired: 'Passwortänderung erforderlich',
  changePasswordRequiredHint: 'Ändere dein Anfangspasswort, bevor du weitermachst.',
  currentPassword: 'Aktuelles Passwort',
  newPassword: 'Neues Passwort',
  changePasswordSubmit: 'Passwort ändern',
  passwordMismatch: 'Die Passwortwiederholung stimmt nicht überein.',
  save: 'Speichern',
  userNameColumn: 'Name',
  userUsernameColumn: 'Benutzername',
  userRoleColumn: 'Rolle',
  userStatusColumn: 'Status',
  userCreatedColumn: 'Angelegt am',
  userActionsColumn: 'Aktionen',
  adminRole: 'Administrator',
  userRole: 'Benutzer',
  active: 'Aktiv',
  blocked: 'Gesperrt',
  createUser: 'Benutzer anlegen',
  createUserTitle: 'Neuen Benutzer anlegen',
  initialPassword: 'Anfangspasswort',
  role: 'Rolle',
  cancel: 'Abbrechen',
  lock: 'Sperren',
  unlock: 'Entsperren',
  lockConfirm: 'Benutzer wirklich sperren?',
  unlockConfirm: 'Benutzer wirklich entsperren?',
  close: 'Schließen',
  requestError: 'Die Anfrage konnte nicht verarbeitet werden.',
  noUsers: 'Keine Benutzer vorhanden.',
  statusError: 'Der Dienststatus konnte nicht abgerufen werden.'
} as const;
